version: 2110.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
environment:
  NuGetApiKey:
    secure: HG+gRzannxVOGKIAOMWiCXyQv0NWOKR2iSBEP2vceWY=
  Module: J81.TestModule
  Source: J81.TestModule
  GitHubKey:
    secure: 6Dtz28d/0iiiZMdamhTBoN+wtOQoF2t8BIbLx0jwduyOW1bEe8NNFaDwe9bM89Y3
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\GitHub.ps1
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
- ps: . .\ci\GitHub.ps1
deploy_script:
- ps: . .\ci\Deploy.ps1

skip_commits:
  message: /AppVeyor validate.*|Merge branch 'main' of.*|Update docs.*/

only_commits:
  files:
    - J81.TestModule/**/*